version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install -y docker

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Building backend image..."
      - docker build -t backend ./../back-end

      - echo "Building frontend image..."
      - docker build -t frontend ./../front-end

  post_build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - '**/*'
